language: python
python: 2.7
env:
  matrix:
    - CONF=travis.cfg
    - CONF=extras.cfg EXTRAS_INSTALLED=true
install:
  - python bootstrap.py -v 1.7.1
  - bin/buildout -c $CONF annotate
  - bin/buildout -N -t 3 -c $CONF
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/csslint --version
  - bin/jshint --version
